name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        - name: HTML5 Validator
        uses: Cyb3r-Jak3/html5validator-action@v0.4
        with:
          # Path of the files to test
          root: # default is .
          # Extra arguments to test with
          extra: # optional
          # Format for logging output. Valid values: gnu,xml,json,text
          format: # optional
          # Logging Level. Valid values: DEBUG, INFO, WARNING. Default: WARNING
          log_level: # optional, default is WARNING
          # Checks css as well
          css: # optional
          # Flag that increase verbose output only used for troubleshooting the action.
          action_debug: # optional
